language: node_js
node_js:
  - 4
  - 5
script:
  - ./node_modules/.bin/mocha --reporter spec test
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: change
    on_failure: always
